# Generated by Django 4.0.3 on 2022-03-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
    ]
