# Generated by Django 4.0.3 on 2022-03-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_city_province'),
        ('post', '0004_remove_post_city_post_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
