# Generated by Django 4.0.3 on 2022-04-13 13:09

from django.db import migrations


def dump_provinces(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Province = apps.get_model('location', 'Province')
    provinces = [
        'آذربایجان شرقی',
        'آذربایجان غربی',
        'اردبیل',
        'اصفهان',
        'البرز',
        'ایلام',
        'بوشهر',
        'تهران',
        'چهارمحال و بختیاری',
        'خراسان جنوبی',
        'خراسان رضوی',
        'خراسان شمالی',
        'خوزستان',
        'زنجان',
        'سمنان',
        'سیستان و بلوچستان',
        'فارس',
        'قزوین',
        'قم',
        'کردستان',
        'کرمان',
        'کرمانشاه',
        'کهگیلویه و بویراحمد',
        'گلستان',
        'گیلان',
        'لرستان',
        'مازندران',
        'مرکزی',
        'هرمزگان',
        'همدان',
        'یزد',
    ]
    for province in provinces:
        Province.objects.create(title=province)


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_delete_city'),
    ]

    operations = [
        migrations.RunPython(dump_provinces),
    ]
