# Generated by Django 4.0.3 on 2022-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='', verbose_name='profile-pic/'),
            preserve_default=False,
        ),
    ]
