# Generated by Django 4.0.3 on 2022-04-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_postwelfare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostWelfare',
            new_name='PostWelfarePlace',
        ),
    ]
